version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 80:80
    working_dir: /app-frontend
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      timeout: 10s
      retries: 5
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 8080:8080
    working_dir: /app-backend
    command: dev
    volumes:
      - ./backend/src:/app-backend
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:80"]
      timeout: 10s
      retries: 5
